# Generated by Django 5.2.17 on 2026-08-10 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(default='manual', max_length=100)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(default='manual', max_length=100)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=160)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('allocated_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('actual_spending', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_records', to='geography.county')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CitizenSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(default='manual', max_length=100)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=160)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('resolved_count', models.PositiveIntegerField(default=0)),
                ('average_response_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizen_signals', to='geography.county')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExecutiveReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(default='manual', max_length=100)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=80)),
                ('period_label', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('review', 'Under review'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='operations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(default='manual', max_length=100)),
                ('source_record_id', models.CharField(blank=True, max_length=255)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('at_risk', 'At risk'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='open', max_length=20)),
                ('due_date', models.DateField()),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='geography.county')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='operations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
