import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geography", "0001_initial"),
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_system", models.CharField(default="manual", max_length=100)),
                ("source_record_id", models.CharField(blank=True, max_length=255)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=280)),
                ("summary", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("kind", models.CharField(choices=[("news", "News"), ("tourism", "Tourism"), ("notice", "Notice"), ("report", "Report")], default="news", max_length=20)),
                ("published_at", models.DateField()),
                ("source_url", models.URLField(blank=True)),
                ("source_label", models.CharField(default="استانداری سمنان", max_length=120)),
                ("sentiment_score", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ("importance", models.PositiveSmallIntegerField(default=3)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("county", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="news_articles", to="geography.county")),
            ],
            options={"ordering": ["-published_at", "-importance", "title"]},
        ),
        migrations.CreateModel(
            name="SectorIndicator",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_system", models.CharField(default="manual", max_length=100)),
                ("source_record_id", models.CharField(blank=True, max_length=255)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=80)),
                ("domain", models.CharField(max_length=80)),
                ("label", models.CharField(max_length=180)),
                ("value", models.DecimalField(decimal_places=2, max_digits=14)),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("period_label", models.CharField(max_length=80)),
                ("trend_percent", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("benchmark_value", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("status", models.CharField(choices=[("healthy", "Healthy"), ("attention", "Attention"), ("critical", "Critical")], default="healthy", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("county", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sector_indicators", to="geography.county")),
            ],
            options={"ordering": ["domain", "label", "county__name"]},
        ),
        migrations.CreateModel(
            name="ProcurementNotice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_system", models.CharField(default="manual", max_length=100)),
                ("source_record_id", models.CharField(blank=True, max_length=255)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=280)),
                ("status", models.CharField(choices=[("planned", "Planned"), ("open", "Open"), ("evaluation", "Evaluation"), ("awarded", "Awarded")], default="planned", max_length=20)),
                ("published_at", models.DateField()),
                ("deadline", models.DateField(blank=True, null=True)),
                ("estimated_amount", models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ("procurement_method", models.CharField(default="مناقصه عمومی", max_length=100)),
                ("reference_code", models.CharField(blank=True, max_length=80)),
                ("county", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="procurements", to="geography.county")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="procurements", to="operations.organization")),
            ],
            options={"ordering": ["-published_at", "title"]},
        ),
        migrations.CreateModel(
            name="SpeechInsight",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_system", models.CharField(default="manual", max_length=100)),
                ("source_record_id", models.CharField(blank=True, max_length=255)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("speaker", models.CharField(max_length=160)),
                ("role", models.CharField(max_length=160)),
                ("spoken_at", models.DateField()),
                ("topic", models.CharField(max_length=120)),
                ("summary", models.TextField()),
                ("commitment_text", models.TextField(blank=True)),
                ("commitment_status", models.CharField(choices=[("open", "Open"), ("in_progress", "In progress"), ("completed", "Completed"), ("at_risk", "At risk")], default="open", max_length=20)),
                ("source_url", models.URLField(blank=True)),
                ("county", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="speech_insights", to="geography.county")),
            ],
            options={"ordering": ["-spoken_at", "topic"]},
        ),
        migrations.CreateModel(
            name="PerformanceIndicator",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_system", models.CharField(default="manual", max_length=100)),
                ("source_record_id", models.CharField(blank=True, max_length=255)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("category", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=180)),
                ("score", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("target", models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ("period_label", models.CharField(max_length=80)),
                ("weight", models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="performance_indicators", to="operations.organization")),
            ],
            options={"ordering": ["organization__name", "category", "label"]},
        ),
        migrations.CreateModel(
            name="CrisisSignal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_system", models.CharField(default="manual", max_length=100)),
                ("source_record_id", models.CharField(blank=True, max_length=255)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=240)),
                ("category", models.CharField(max_length=100)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="medium", max_length=20)),
                ("status", models.CharField(choices=[("open", "Open"), ("monitoring", "Monitoring"), ("resolved", "Resolved")], default="monitoring", max_length=20)),
                ("occurred_at", models.DateField()),
                ("impact_score", models.PositiveSmallIntegerField(default=0)),
                ("summary", models.TextField(blank=True)),
                ("source_label", models.CharField(default="سامانه پایش", max_length=120)),
                ("county", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="crisis_signals", to="geography.county")),
            ],
            options={"ordering": ["-occurred_at", "-impact_score", "title"]},
        ),
        migrations.CreateModel(
            name="ForecastSignal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_system", models.CharField(default="manual", max_length=100)),
                ("source_record_id", models.CharField(blank=True, max_length=255)),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("domain", models.CharField(max_length=100)),
                ("metric_label", models.CharField(max_length=180)),
                ("as_of", models.DateField()),
                ("horizon_label", models.CharField(max_length=80)),
                ("current_value", models.DecimalField(decimal_places=2, max_digits=14)),
                ("forecast_value", models.DecimalField(decimal_places=2, max_digits=14)),
                ("lower_bound", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("upper_bound", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("risk_level", models.CharField(choices=[("healthy", "Healthy"), ("attention", "Attention"), ("critical", "Critical")], default="healthy", max_length=20)),
                ("confidence", models.PositiveSmallIntegerField(default=0)),
                ("methodology", models.CharField(blank=True, max_length=180)),
                ("county", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="forecast_signals", to="geography.county")),
            ],
            options={"ordering": ["domain", "metric_label", "county__name"]},
        ),
        migrations.AddConstraint(
            model_name="sectorindicator",
            constraint=models.UniqueConstraint(fields=("code", "period_label", "county"), name="uniq_indicator_period_county"),
        ),
        migrations.AddConstraint(
            model_name="performanceindicator",
            constraint=models.UniqueConstraint(fields=("organization", "label", "period_label"), name="uniq_org_kpi_period"),
        ),
    ]
