# Generated by Django 5.2.16 on 2026-08-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='ai_confidence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='ai_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='kind',
            field=models.CharField(choices=[('news', 'News'), ('tourism', 'Tourism'), ('culture', 'Culture & heritage'), ('notice', 'Notice'), ('report', 'Report'), ('speech', 'Speech'), ('procurement', 'Procurement'), ('project', 'Project'), ('crisis', 'Crisis'), ('sector', 'Sector intelligence'), ('investment', 'Investment'), ('other', 'Other')], default='news', max_length=20),
        ),
    ]
