# Generated by Django 5.2.17 on 2026-08-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_entity__0bff9a_idx',
            old_name='audit_event_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_created_7710b7_idx',
            old_name='audit_event_created_idx',
        ),
    ]
