# Generated by Django 5.2.16 on 2026-08-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rawcontent',
            new_name='ingestion_r_content_5cf6fb_idx',
            old_name='ingestion_r_content_6f2dbd_idx',
        ),
    ]
